CREATE TABLE A (
	id INT PRIMARY KEY
);

CREATE TABLE AB (
	id INT PRIMARY KEY,
	a_id INT NOT NULL,
	b_id INT NOT NULL
);

CREATE TABLE B (
	id INT PRIMARY KEY,
	c_id INT NOT NULL
);

CREATE TABLE C (
	id INT PRIMARY KEY
);


-- all ids = 1						=> KO
INSERT INTO A VALUES (1);
INSERT INTO AB VALUES (1, 1, 1);
INSERT INTO B VALUES (1, 1);
INSERT INTO C VALUES (1);

-- AB.id is different				=> KO
INSERT INTO A VALUES (2);
INSERT INTO AB VALUES (20, 2, 2);
INSERT INTO B VALUES (2, 2);
INSERT INTO C VALUES (2);

-- C.id is different				=> KO
INSERT INTO A VALUES (3);
INSERT INTO AB VALUES (3, 3, 3);
INSERT INTO B VALUES (3, 30);
INSERT INTO C VALUES (30);

-- A.id != B.id						=> works
INSERT INTO A VALUES (4);
INSERT INTO AB VALUES (4, 4, 40);
INSERT INTO B VALUES (40, 4);
INSERT INTO C VALUES (4);
